### ISSUE TITLE
Auth/Calendar.js examples

### ISSUE THREAD

**Issue by Jarvvski** [ahansrisuk/startpage#1]
Hey, found you via reddit. Not sure what I should be putting in `auth|calendar.js`. The readme isn't particularly helpful there

Please help out a Vue noob.

**Comment by ahansrisuk** [comment]
Hi, no worries! I didn't expect this to take off like it did. Apologies for not being more clear. I'll push an update to the readme when I have some time. I'm still very much a noob.

If you're referring to this line in the Calendar.vue file:
`import calendars from '../../calendars';const calendarList = calendars.ids`

You simply need a calendars.js file (in my case its in the root). This should be formatted as such:
`export default {
    ids: ['id_of_your_google_calendar']
}`
You can have multiple ids in that array. 

Here's an example of the auth.js file if you need it:
`export default {
    darksky: 'xxxxxxxxxxxxxxx',
    api_key: 'xxxxxxxxxxxxxx',
    client_id: 'xxxxxxxxxxxxxx',
    scopes: 'xxxxxxxxxxxxxxx'
}`
